# Generated by Django 4.1.7 on 2023-03-09 17:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("copies", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="loan",
            name="copy",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_copy_borrowed",
                to="copies.copy",
            ),
        ),
        migrations.AlterField(
            model_name="loan",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="copy_borrowed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
