# Generated by Django 4.1.7 on 2023-03-09 17:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("copies", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Loan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_receipt", models.DateField(auto_now_add=True)),
                ("date_devolution", models.DateField()),
                ("is_receipt", models.BooleanField(default=False)),
                ("price", models.IntegerField()),
                (
                    "copy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copy_borrowed",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_copy_borrowed",
                        to="copies.copy",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="copy",
            name="users_loan",
            field=models.ManyToManyField(
                related_name="copies_loan",
                through="copies.Loan",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
